/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.2.1
 *
 * Project: 'stm32.Debug+Nucleo_STM32F4466' 
 * Target:  'Debug+Nucleo_STM32F4466' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H

/* Keil::Device:CubeMX@1.0.0 */
#define RTE_DEVICE_CUBE_MX
        #define CMSIS_device_header "stm32f4xx.h"


#endif /* RTE_COMPONENTS_H */
